In [39]:
import pandas as pd
df=pd.read_csv('/content/FINANCAL _DATASET.csv')

In [40]:
df.shape

(20, 14)

In [41]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Employment_Type', 'Annual_Income',
       'Loan_Type', 'Loan_Amount', 'Loan_Tenure_Months', 'Interest_Rate',
       'Credit_Score', 'EMI_Amount', 'Loan_Status', 'Default_Status',
       'Region'],
      dtype='object')

In [42]:
df.head()

,Customer_ID,Age,Gender,Employment_Type,Annual_Income,Loan_Type,Loan_Amount,Loan_Tenure_Months,Interest_Rate,Credit_Score,EMI_Amount,Loan_Status,Default_Status,Region
0,C001,32.0,Male,Salaried,450000.0,Vehicle,300000.0,36.0,12.5,720.0,10050.0,Approved,No,South
1,C002,45.0,Female,Self-Employed,NaN,Business,500000.0,48.0,14.0,680.0,13800.0,Approved,Yes,West
2,C003,29.0,NaN,Salaried,350000.0,Personal,200000.0,24.0,11.0,750.0,9400.0,Approved,No,South
3,C004,40.0,Male,Self-Employed,800000.0,Vehicle,700000.0,NaN,15.5,640.0,16800.0,Approved,Yes,North
4,C005,NaN,Female,Salaried,300000.0,Personal,150000.0,24.0,10.5,780.0,NaN,Approved,No,East

In [43]:
df.tail()

,Customer_ID,Age,Gender,Employment_Type,Annual_Income,Loan_Type,Loan_Amount,Loan_Tenure_Months,Interest_Rate,Credit_Score,EMI_Amount,Loan_Status,Default_Status,Region
15,C016,39.0,Female,Salaried,520000.0,Vehicle,360000.0,36.0,13.5,700.0,12000.0,NaN,No,South
16,C017,52.0,Male,Self-Employed,950000.0,Business,750000.0,60.0,17.0,NaN,19000.0,Approved,Yes,North
17,C018,33.0,Female,Salaried,NaN,Personal,210000.0,36.0,11.9,725.0,7200.0,Approved,NaN,East
18,C019,48.0,Male,Self-Employed,820000.0,Vehicle,600000.0,48.0,15.0,655.0,16000.0,Approved,Yes,West
19,C020,30.0,Female,Salaried,390000.0,Personal,190000.0,NaN,11.3,755.0,8800.0,Approved,No,South

In [44]:
df.describe()

,Age,Annual_Income,Loan_Amount,Loan_Tenure_Months,Interest_Rate,Credit_Score,EMI_Amount
count,18.000000,18.000000,19.000000,18.000000,18.000000,18.000000,19.000000
mean,38.500000,574444.444444,373684.210526,39.333333,13.222222,703.611111,12055.263158
std,7.905694,218664.992820,199282.338135,11.499361,2.118700,49.935416,3926.437979
min,27.000000,300000.000000,140000.000000,24.000000,10.500000,620.000000,6600.000000
25%,32.250000,397500.000000,205000.000000,36.000000,11.425000,662.500000,8650.000000
50%,38.500000,490000.000000,320000.000000,36.000000,12.600000,707.500000,11800.000000
75%,44.750000,787500.000000,525000.000000,48.000000,14.950000,746.250000,15500.000000
max,52.000000,950000.000000,750000.000000,60.000000,17.000000,780.000000,19000.000000

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         20 non-null     object
 1   Age                 18 non-null     float64
 2   Gender              19 non-null     object
 3   Employment_Type     19 non-null     object
 4   Annual_Income       18 non-null     float64
 5   Loan_Type           19 non-null     object
 6   Loan_Amount         19 non-null     float64
 7   Loan_Tenure_Months  18 non-null     float64
 8   Interest_Rate       18 non-null     float64
 9   Credit_Score        18 non-null     float64
 10  EMI_Amount          19 non-null     float64
 11  Loan_Status         18 non-null     object
 12  Default_Status      18 non-null     object
 13  Region              18 non-null     object
dtypes: float64(7), object(7)
memory usage: 2.3+ KB

In [46]:
df.isnull()

,Customer_ID,Age,Gender,Employment_Type,Annual_Income,Loan_Type,Loan_Amount,Loan_Tenure_Months,Interest_Rate,Credit_Score,EMI_Amount,Loan_Status,Default_Status,Region
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,False,False,False,False
4,False,True,False,False,False,False,False,False,False,False,True,False,False,False
5,False,False,False,False,False,False,True,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,True,False,False,False,False,True
7,False,False,False,False,False,False,False,False,False,True,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,True,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,True,False
10,False,False,False,True,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,True
12,False,True,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,True,False,False,False,False,False
14,False,False,False,False,False,True,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,True,False,False
16,False,False,False,False,False,False,False,False,False,True,False,False,False,False
17,False,False,False,False,True,False,False,False,False,False,False,False,True,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,True,False,False,False,False,False,False

In [47]:
df.isnull().sum()

Customer_ID           0
Age                   2
Gender                1
Employment_Type       1
Annual_Income         2
Loan_Type             1
Loan_Amount           1
Loan_Tenure_Months    2
Interest_Rate         2
Credit_Score          2
EMI_Amount            1
Loan_Status           2
Default_Status        2
Region                2
dtype: int64

In [48]:
df.isnull().sum().sum()

np.int64(21)

In [56]:
df.duplicated().sum()

np.int64(0)

In [57]:
df.dropna(inplace=True)

In [59]:
df

,Customer_ID,Age,Gender,Employment_Type,Annual_Income,Loan_Type,Loan_Amount,Loan_Tenure_Months,Interest_Rate,Credit_Score,EMI_Amount,Loan_Status,Default_Status,Region
0,C001,32.0,Male,Salaried,450000.0,Vehicle,300000.0,36.0,12.5,720.0,10050.0,Approved,No,South
18,C019,48.0,Male,Self-Employed,820000.0,Vehicle,600000.0,48.0,15.0,655.0,16000.0,Approved,Yes,West